#!/bin/bash
#
#  i3-backlight-clean
#
#   A minimal and cleaned version of i3-backlight control notifications for i3wm.
#
#  Requires:
#    brightnessctl
#    cut (POSIX compatible)
#
#  Optional:
#    A libnotify compatible notification daemon such as notify-osd or dunst
#    notify-send (libnotify) or dunstify (dunst)
#
#  License: GNU General Public License v2
#  Author: lemon-hope
#  Inspired by / cloned from : https://github.com/fmorisan/i3-backlight/tree/master  

# Get the backlight as a percentage.
get_backlight() {
	brightnessctl | grep 'Current brightness' | cut -d' ' -f4 | tr -d '()'

}


# Increase brightness relative to current value.
#
# Arguments:
#   Step        (integer) Percentage to increase by.
raise_backlight() {
    brightnessctl set +"$1"%
}


# Decrease brightness relative to current value.
#
# Arguments:
#   Step        (integer) Percentage to decrease by.
lower_backlight() {
    brightnessctl set "$1"%-
}


# Display a notification indicating the current brightness level.
notify_backlight() {
    local br=$(get_backlight)
    local icon="display-brightness-symbolic"
    local text="Brightness ${br}"

    if $opt_show_backlight_progress; then
        local progress=$(get_progress_bar "$br")
        text="$text $progress"
    fi

    dunstify -i "$icon" -t "$expires" -h int:value:"$br" -h string:synchronous:brightness "$text" -r 1000
}


# Generates a progress bar for the provided value.
#
# Arguments:
#   Percentage      (integer) Percentage of progress.
#   Maximum         (integer) Maximum percentage. (default: 100)
#   Divisor         (integer) For calculating the ratio of blocks to progress (default: 5)
#
# Returns:
#   The progress bar.
get_progress_bar() {
    local percent="$1"
    local max_percent=${2:-100}
    local divisor=${3:-5}
    local progress=$((($percent > $max_percent ? $max_percent : $percent) / $divisor))

    printf '█%.0s' $(eval echo "{1..$progress}")
}

# Display program usage.
usage() {
    echo "Usage: $0 [options]
Control volume and related notifications.

Options:
  -d <amount>       decrease brightness 
  -e <expires>      expiration time of notifications, in milliseconds
  -i <amount>       increase brightness
  -n                show notifications
  -p                show text volume progress bar
  -y                use dunstify instead of notify-send
  -h                display this help and exit
" 1>&2
    exit 1
}
###########################################################

opt_decrease_backlight=false
opt_increase_backlight=false
opt_notification=false
opt_set_backlight=false
opt_show_backlight_progress=false
opt_use_dunstify=false
step=5
expires="1500"

while getopts "d:e:hi:n:y" o; do
    case "$o" in
        d)
            opt_decrease_backlight=true
            step="${OPTARG}"
            ;;
        e)
            expires="${OPTARG}"
            ;;
        i)
            opt_increase_backlight=true
            step="${OPTARG}"
            ;;
        n)
            opt_notification=true
            ;;
        y)
            opt_use_dunstify=true
            ;;
        h | *)
            usage
            ;;
    esac
done
shift $((OPTIND-1)) # Shift off options and optional --

if ${opt_increase_backlight}; then
    raise_backlight $step
fi

if ${opt_decrease_backlight}; then
    lower_backlight $step
fi


# The options below this line must be last
if ${opt_notification}; then
    notify_backlight
fi

